[package]
name = "plag"
version = "0.1.0"
authors = ["Oskari Timperi <oskari.timperi@iki.fi>"]
license = "GPL-3.0-or-later"

[dependencies]
geojson = "0.13.0"
geo-types = "0.2.2"
kamadak-exif = "0.3.1"
serde_json = "1.0.33"
clap = "2.32.0"
